DELETE FROM APP.ESTACIONENTITY_CALIFICACIONENTITY;
DELETE FROM APP.BICICLETAENTITY_ACCESORIOBICICLETAENTITY;
DELETE FROM APP.DIRECCIONENTITY_ESTACIONENTITY;
DELETE FROM APP.DIRECCIONENTITY_USUARIOENTITY;
DELETE FROM APP.ESTACIONENTITY_BICICLETAENTITY;
DELETE FROM APP.ESTACIONENTITY_DIRECCIONENTITY;
DELETE FROM APP.ESTACIONENTITY_RESERVAENTITY;
DELETE FROM APP.RESERVAENTITY_ESTACIONENTITY;
DELETE FROM APP.USUARIOENTITY_PUNTOENTITY;
DELETE FROM APP.USUARIOENTITY_RESERVAENTITY;
DELETE FROM APP.ACCESORIOBICICLETAENTITY;
DELETE FROM APP.ACCESORIOENTITY;
DELETE FROM APP.BICICLETAENTITY;
DELETE FROM APP.CALIFICACIONENTITY;
DELETE FROM APP.DIRECCIONENTITY;
DELETE FROM APP.ESTACIONENTITY;
DELETE FROM APP.PAGOENTITY;
DELETE FROM APP.PUNTOENTITY;
DELETE FROM APP.RESERVAENTITY;
DELETE FROM APP.USUARIOENTITY;


/*No modificar esto - Gabriel Pinto*/
insert into App.DireccionEntity(ID, CIUDAD, CODIGOPOSTAL, DESCRIPCION) values (1, 'Bogota', 11001, 'Direccion 1');
insert into App.DireccionEntity(ID, CIUDAD, CODIGOPOSTAL, DESCRIPCION) values (2, 'Bogota', 11011, 'Direccion 2');
insert into App.DireccionEntity(ID, CIUDAD, CODIGOPOSTAL, DESCRIPCION) values (3, 'Bogota', 11111, 'Direccion 3');

insert into App.USUARIOENTITY(ID, DOCUMENTOUSUARIO, FECHANACIMIENTO, NAME, TIPOID) values (1, 123456789, '09/14/1990', 'Usuario 1', 1);
insert into App.USUARIOENTITY(ID, DOCUMENTOUSUARIO, FECHANACIMIENTO, NAME, TIPOID) values (2, 223456789, '10/15/1997', 'Usuario 2', 1);
insert into App.USUARIOENTITY(ID, DOCUMENTOUSUARIO, FECHANACIMIENTO, NAME, TIPOID) values (3, 323232323, '08/13/1997', 'Usuario 2', 1);

insert into App.ESTACIONENTITY(ID, NAME) values (1, 'Estacion 1');
insert into App.ESTACIONENTITY(ID, NAME) values (2, 'Estacion 2');
insert into App.ESTACIONENTITY(ID, NAME) values (3, 'Estacion 3');
insert into App.ESTACIONENTITY(ID, NAME) values (4, 'Estacion 4');

insert into App.BICICLETAENTITY(ID, ESTADO, MARCA, MODELO, ESTACION_ID) values (1, 2, 'Marca 1', 'Modelo 1', 1);
insert into App.BICICLETAENTITY(ID, ESTADO, MARCA, MODELO, ESTACION_ID) values (2, 2, 'Marca 2', 'Modelo 2', 2);
insert into App.BICICLETAENTITY(ID, ESTADO, MARCA, MODELO, ESTACION_ID) values (3, 2, 'Marca 3', 'Modelo 3', 2);

insert into App.RESERVAENTITY(ID, ESTADO, FECHAINICIO, FECHAENTREGA, PRECIOFINAL, ESTACIONLLEGADA_ID, ESTACIONSALIDA_ID, USUARIORESERVA_ID) values(1, 1, '09/20/2017', '09/28/2017', 40000, 1, 2, 1);
insert into App.RESERVAENTITY(ID, ESTADO, FECHAINICIO, FECHAENTREGA, PRECIOFINAL, ESTACIONLLEGADA_ID, ESTACIONSALIDA_ID, USUARIORESERVA_ID) values(2, 1, '09/22/2017', '09/29/2017', 20000, 2, 2, 1);
insert into App.RESERVAENTITY(ID, ESTADO, FECHAINICIO, FECHAENTREGA, PRECIOFINAL, ESTACIONLLEGADA_ID, ESTACIONSALIDA_ID, USUARIORESERVA_ID) values(3, 0, '09/24/2017', '09/25/2017', 10000, 1, 1, 2);

insert into App.USUARIOENTITY_RESERVAENTITY(USUARIOENTITY_ID, RESERVAS_ID) values (1, 1);
insert into App.USUARIOENTITY_RESERVAENTITY(USUARIOENTITY_ID, RESERVAS_ID) values (1, 2);
insert into App.USUARIOENTITY_RESERVAENTITY(USUARIOENTITY_ID, RESERVAS_ID) values (2, 3);


insert into App.ESTACIONENTITY_RESERVAENTITY(ESTACIONENTITY_ID, RESERVAS_ID) values (2,1);
insert into App.ESTACIONENTITY_RESERVAENTITY(ESTACIONENTITY_ID, RESERVAS_ID) values (2,2);
insert into App.ESTACIONENTITY_RESERVAENTITY(ESTACIONENTITY_ID, RESERVAS_ID) values (1,3);

INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (1, '09/20/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (2, '09/21/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (3, '09/22/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (4, '09/23/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (5, '09/24/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (6, '09/25/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (7, '09/26/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (8, '09/26/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (9, '09/27/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (10, '09/28/2017', 2);

INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 1);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 2);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 3);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 4);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 5);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 6);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 7);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 8);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 9);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 10);


/*Agregar desde acá si quieren*/
