/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  gl.pinto10
 * Created: 28/09/2017
 */
DELETE FROM APP.BICICLETAENTITY_ACCESORIOBICICLETAENTITY;
DELETE FROM APP.DIRECCIONENTITY_ESTACIONENTITY;
DELETE FROM APP.DIRECCIONENTITY_USUARIOENTITY;
DELETE FROM APP.ESTACIONENTITY_BICICLETAENTITY;
DELETE FROM APP.ESTACIONENTITY_DIRECCIONENTITY;
DELETE FROM APP.ESTACIONENTITY_RESERVAENTITY;
DELETE FROM APP.RESERVAENTITY_ESTACIONENTITY;
DELETE FROM APP.USUARIOENTITY_PUNTOENTITY;
DELETE FROM APP.USUARIOENTITY_RESERVAENTITY;
DELETE FROM APP.ACCESORIOBICICLETAENTITY;
DELETE FROM APP.ACCESORIOENTITY;
DELETE FROM APP.BICICLETAENTITY;
DELETE FROM APP.CALIFICACIONENTITY;
DELETE FROM APP.DIRECCIONENTITY;
DELETE FROM APP.ESTACIONENTITY;
DELETE FROM APP.PAGOENTITY;
DELETE FROM APP.PUNTOENTITY;
DELETE FROM APP.RESERVAENTITY;
DELETE FROM APP.USUARIOENTITY;

INSERT INTO APP.ESTACIONENTITY(ID, "NAME") VALUES (1, 'Esta 1');
INSERT INTO APP.ESTACIONENTITY(ID, "NAME") VALUES (2, 'Esta 2');

INSERT INTO APP.USUARIOENTITY(ID, "NAME") VALUES (1, 'Usu 1');
INSERT INTO APP.USUARIOENTITY(ID, "NAME") VALUES (2, 'Usu 2');

INSERT INTO APP.RESERVAENTITY(ID, USUARIORESERVA_ID, ESTACIONLLEGADA_ID, ESTACIONSALIDA_ID, PRECIOFINAL) VALUES (1, 1, 1, 2, 2000);
INSERT INTO APP.RESERVAENTITY(ID, USUARIORESERVA_ID, ESTACIONLLEGADA_ID, ESTACIONSALIDA_ID) VALUES (2, 2, 2, 1);

INSERT INTO APP.USUARIOENTITY_RESERVAENTITY(USUARIOENTITY_ID, RESERVAS_ID) VALUES (1, 1);
INSERT INTO APP.USUARIOENTITY_RESERVAENTITY(USUARIOENTITY_ID, RESERVAS_ID) VALUES (2, 2);



