/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  gl.pinto10
 * Created: 28/09/2017
 */
DELETE FROM APP.BICICLETAENTITY_ACCESORIOBICICLETAENTITY;
DELETE FROM APP.DIRECCIONENTITY_ESTACIONENTITY;
DELETE FROM APP.DIRECCIONENTITY_USUARIOENTITY;
DELETE FROM APP.ESTACIONENTITY_BICICLETAENTITY;
DELETE FROM APP.ESTACIONENTITY_DIRECCIONENTITY;
DELETE FROM APP.ESTACIONENTITY_RESERVAENTITY;
DELETE FROM APP.RESERVAENTITY_ESTACIONENTITY;
DELETE FROM APP.USUARIOENTITY_PUNTOENTITY;
DELETE FROM APP.USUARIOENTITY_RESERVAENTITY;
DELETE FROM APP.ACCESORIOBICICLETAENTITY;
DELETE FROM APP.ACCESORIOENTITY;
DELETE FROM APP.BICICLETAENTITY;
DELETE FROM APP.CALIFICACIONENTITY;
DELETE FROM APP.DIRECCIONENTITY;
DELETE FROM APP.ESTACIONENTITY;
DELETE FROM APP.PAGOENTITY;
DELETE FROM APP.PUNTOENTITY;
DELETE FROM APP.RESERVAENTITY;
DELETE FROM APP.USUARIOENTITY;

INSERT INTO APP.USUARIOENTITY(ID, DOCUMENTOUSUARIO, FECHANACIMIENTO, "NAME", TIPOID) VALUES (1, 1234, '09/15/1990', 'Usuario 1', 1);
INSERT INTO APP.USUARIOENTITY(ID, DOCUMENTOUSUARIO, FECHANACIMIENTO, "NAME", TIPOID) VALUES (2, 5678, '10/15/1992', 'Usuario 2', 1);

INSERT INTO APP.RESERVAENTITY(ID, ESTADO) VALUES (1, 0);

INSERT INTO APP.USUARIOENTITY_RESERVAENTITY(USUARIOENTITY_ID, RESERVAS_ID) VALUES (1, 1);

INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (1, '09/20/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (2, '09/21/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (3, '09/22/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (4, '09/23/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (5, '09/24/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (6, '09/25/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (7, '09/26/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (8, '09/26/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (9, '09/27/2017', 2);
INSERT INTO APP.PUNTOENTITY(ID, FECHAPUNTO, USUARIOPUNTO_ID) VALUES (10, '09/28/2017', 2);

INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 1);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 2);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 3);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 4);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 5);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 6);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 7);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 8);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 9);
INSERT INTO APP.USUARIOENTITY_PUNTOENTITY(USUARIOENTITY_ID, PUNTOS_ID) VALUES (2, 10);

 




